/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qui;

import database.IInfoController;
import database.transactions.AccountInformation;
import database.transactions.MoneyOrder;
import java.awt.Color;
import javax.swing.JOptionPane;
import qui.setting.ActionSetting;
import qui.setting.ButtonSetting;
import qui.setting.Dialogs;
import qui.setting.IRegulator;
import qui.setting.TextSetting;

/**
 *
 * @author hamza
 */
public class MoneyOrderScreen extends javax.swing.JFrame implements IRegulator,IInfoController{
    private MoneyOrder moneyOrderObject = null;
    private int moneyOrderAmount = 0;
    private final String Account_Number_Original = "Account Number";
    /**
     * Creates new form MoneyOrderScreen
     */
    public MoneyOrderScreen() {
        initComponents();
        getEdits();
    }

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setFocusable(true);
        accountNumberText.setText(Account_Number_Original);
        TextSetting.setOnlyNumber(moneyOrderAmountText);
        TextSetting.setOnlyNumber(accountNumberText);
        TextSetting.setMaxLimit(moneyOrderAmountText, 5);
//        TextSetting.setMaxLimit(accountNumberText,11);
        this.userNameSurname.setText("Sayın " + getAccountInformation().getNameSurname());
        this.balanceLabel2.setText(String.valueOf(getAccountInformation().getBalance()));
        
    }

    @Override
    public boolean validInformation() {
        return !(this.moneyOrderAmountText.getText().equals("")
                || this.accountNumberText.getText().equals(this.Account_Number_Original));
    }

    @Override
    public AccountInformation getAccountInformation() {
        return AccountInformation.getInstance();
    }

    public MoneyOrder getMoneyOrderObject() {
       if(this.moneyOrderObject == null) {
            moneyOrderObject = new MoneyOrder();
        }
        return moneyOrderObject;
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawCashPanel = new javax.swing.JPanel();
        userNameSurname = new javax.swing.JLabel();
        limitLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        balanceLabel2 = new javax.swing.JLabel();
        amountLabel = new javax.swing.JLabel();
        moneyOrderAmountText = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        amountLabel1 = new javax.swing.JLabel();
        accountNumberText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawCashPanel.setBackground(new java.awt.Color(153, 255, 102));

        userNameSurname.setBackground(new java.awt.Color(204, 204, 255));
        userNameSurname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userNameSurname.setForeground(new java.awt.Color(255, 0, 0));
        userNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userNameSurname.setText("[USER NAME AND SURNAME]");

        limitLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        limitLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        limitLabel.setText(" You can deposit maksimum 20000 TL at once");

        balanceLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceLabel.setText("Balance :");

        balanceLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceLabel2.setText("[Balance]");

        amountLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountLabel.setText("Amount :");

        moneyOrderAmountText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moneyOrderAmountTextKeyReleased(evt);
            }
        });

        sendButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sendButton.setText("Draw Cash");
        sendButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sendButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sendButtonMouseExited(evt);
            }
        });
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        amountLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        amountLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amountLabel1.setText("Account Number : ");

        accountNumberText.setForeground(new java.awt.Color(153, 153, 153));
        accountNumberText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                accountNumberTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                accountNumberTextFocusLost(evt);
            }
        });

        javax.swing.GroupLayout drawCashPanelLayout = new javax.swing.GroupLayout(drawCashPanel);
        drawCashPanel.setLayout(drawCashPanelLayout);
        drawCashPanelLayout.setHorizontalGroup(
            drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawCashPanelLayout.createSequentialGroup()
                .addGroup(drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drawCashPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(userNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drawCashPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drawCashPanelLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(limitLabel))
                    .addGroup(drawCashPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(drawCashPanelLayout.createSequentialGroup()
                                .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(moneyOrderAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(drawCashPanelLayout.createSequentialGroup()
                                .addComponent(amountLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, drawCashPanelLayout.createSequentialGroup()
                                .addComponent(balanceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(balanceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drawCashPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        drawCashPanelLayout.setVerticalGroup(
            drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drawCashPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(userNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(limitLabel)
                .addGap(28, 28, 28)
                .addGroup(drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(balanceLabel2))
                .addGap(28, 28, 28)
                .addGroup(drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyOrderAmountText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(drawCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(drawCashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(drawCashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moneyOrderAmountTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moneyOrderAmountTextKeyReleased
        
        this.moneyOrderAmount = TextSetting.checkTheTextKeyReleased(moneyOrderAmountText, 20000);
    }//GEN-LAST:event_moneyOrderAmountTextKeyReleased

    private void sendButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseEntered
        ButtonSetting.setBgFg(sendButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_sendButtonMouseEntered

    private void sendButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendButtonMouseExited
        ButtonSetting.setOriginalBgFg(sendButton);
    }//GEN-LAST:event_sendButtonMouseExited

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
         if(this.validInformation()) {
            this.makeMoneyOrder();
        } else {
            Dialogs.notEmptyMessageShow(this);
        }
        
        
        
        
    }//GEN-LAST:event_sendButtonActionPerformed
    
     private void makeMoneyOrder() {
        getMoneyOrderObject().setSendAmount(this.moneyOrderAmount);
        getMoneyOrderObject().setRemittanceCreditPerson(this.accountNumberText.getText());
        
        if(getMoneyOrderObject().isMoneyOrder()) {
            Dialogs.privateMessageShow(this, "The transfer has been successfully completed.\n"
                    + "Sent account number:" + this.accountNumberText.getText()
                    + "\nAmount Sent:" + this.moneyOrderAmount+ " TL");
            ActionSetting.setVisible(this, new AccountScreen());
        } else {
            Dialogs.privateMessageShow(this, "Transfer could not be performed.\n"
                    + "Please check your information!");
        }
    }
     
    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        ButtonSetting.setBgFg(backButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
        ButtonSetting.setOriginalBgFg(backButton);
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ActionSetting.setVisible(this, new AccountScreen());
    }//GEN-LAST:event_backButtonActionPerformed

    private void accountNumberTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountNumberTextFocusGained
         TextSetting.checkTheTextFocusGained(accountNumberText, Account_Number_Original);
    }//GEN-LAST:event_accountNumberTextFocusGained

    private void accountNumberTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accountNumberTextFocusLost
       TextSetting.checkTheTextFocusLost(accountNumberText);
    }//GEN-LAST:event_accountNumberTextFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyOrderScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyOrderScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountNumberText;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JLabel amountLabel1;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balanceLabel2;
    private javax.swing.JPanel drawCashPanel;
    private javax.swing.JLabel limitLabel;
    private javax.swing.JTextField moneyOrderAmountText;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel userNameSurname;
    // End of variables declaration//GEN-END:variables
}
