/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qui;

import database.IInfoController;
import database.transactions.AccountInformation;
import database.transactions.Payments;
import java.awt.Color;
import qui.setting.ActionSetting;
import qui.setting.ButtonSetting;
import qui.setting.Dialogs;
import qui.setting.IRegulator;

/**
 *
 * @author hamza
 */
public class PaymentScreen extends javax.swing.JFrame implements IRegulator,IInfoController{
    private Payments paymentsObject = null;
    /**
     * Creates new form PaymentScreen
     */
    public PaymentScreen() {
        initComponents();
        getEdits();
        
    }

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        this.setFocusable(true);
        this.userNameSurname.setText("Sayın " + getAccountInformation().getNameSurname());
        this.electricDeptLabel.setText(String.valueOf(getAccountInformation().getElectricityBill()));
        this.waterDeptLabel.setText(String.valueOf(getAccountInformation().getWaterBill()));
        this.gasDeptLabel.setText(String.valueOf(getAccountInformation().getGasBill()));
        this.internetDeptLabel.setText(String.valueOf(getAccountInformation().getInternetBill()));
    }

    @Override
    public boolean validInformation() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public AccountInformation getAccountInformation() {
        return AccountInformation.getInstance();
    }

    public Payments getPaymentsObject() {
         if (this.paymentsObject == null) {
            paymentsObject = new Payments();
        }
        return paymentsObject;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        paymentPanel = new javax.swing.JPanel();
        userNameSurname = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        payElectricityBillButton = new javax.swing.JButton();
        waterDeptLabel = new javax.swing.JLabel();
        messagelWaterBillLabel = new javax.swing.JLabel();
        messageGazBillLabel = new javax.swing.JLabel();
        messageInternetBillLabel = new javax.swing.JLabel();
        payWaterBillButton = new javax.swing.JButton();
        payGasBillButton = new javax.swing.JButton();
        payInternetBillButton = new javax.swing.JButton();
        messageElecBillLabel = new javax.swing.JLabel();
        electricDeptLabel = new javax.swing.JLabel();
        internetDeptLabel = new javax.swing.JLabel();
        gasDeptLabel = new javax.swing.JLabel();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JAVA BANK PAYMENT SCREEN");

        paymentPanel.setBackground(new java.awt.Color(153, 255, 102));

        userNameSurname.setBackground(new java.awt.Color(204, 204, 255));
        userNameSurname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userNameSurname.setForeground(new java.awt.Color(255, 0, 0));
        userNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userNameSurname.setText("[USER NAME AND SURNAME]");

        backButton.setText("BACK");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backButtonMouseExited(evt);
            }
        });
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        payElectricityBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payElectricityBillButton.setText("PAY");
        payElectricityBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payElectricityBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payElectricityBillButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payElectricityBillButtonMouseExited(evt);
            }
        });
        payElectricityBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payElectricityBillButtonActionPerformed(evt);
            }
        });

        waterDeptLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        waterDeptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waterDeptLabel.setText("[Water]");

        messagelWaterBillLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        messagelWaterBillLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messagelWaterBillLabel.setText("Total water bill :");

        messageGazBillLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        messageGazBillLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageGazBillLabel.setText("Total gas bill :");

        messageInternetBillLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        messageInternetBillLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageInternetBillLabel.setText("Total internet bill :");

        payWaterBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payWaterBillButton.setText("PAY");
        payWaterBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payWaterBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payWaterBillButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payWaterBillButtonMouseExited(evt);
            }
        });
        payWaterBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payWaterBillButtonActionPerformed(evt);
            }
        });

        payGasBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payGasBillButton.setText("Pay");
        payGasBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payGasBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payGasBillButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payGasBillButtonMouseExited(evt);
            }
        });
        payGasBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payGasBillButtonActionPerformed(evt);
            }
        });

        payInternetBillButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        payInternetBillButton.setText("PAY");
        payInternetBillButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payInternetBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payInternetBillButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payInternetBillButtonMouseExited(evt);
            }
        });
        payInternetBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payInternetBillButtonActionPerformed(evt);
            }
        });

        messageElecBillLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        messageElecBillLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        messageElecBillLabel.setText("Total electricity bill :");

        electricDeptLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        electricDeptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        electricDeptLabel.setText("[Electrik]");

        internetDeptLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        internetDeptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        internetDeptLabel.setText("[İnternet]");

        gasDeptLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        gasDeptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gasDeptLabel.setText("[Gaz]");

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(userNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messagelWaterBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageGazBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(messageInternetBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(electricDeptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(payElectricityBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(internetDeptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(payInternetBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(gasDeptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(payGasBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(waterDeptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(payWaterBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paymentPanelLayout.createSequentialGroup()
                    .addGap(101, 101, 101)
                    .addComponent(messageElecBillLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(430, Short.MAX_VALUE)))
        );

        paymentPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {messageGazBillLabel, messageInternetBillLabel, messagelWaterBillLabel});

        paymentPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {electricDeptLabel, gasDeptLabel, internetDeptLabel, waterDeptLabel});

        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(userNameSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payElectricityBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricDeptLabel))
                .addGap(33, 33, 33)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payWaterBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messagelWaterBillLabel)
                    .addComponent(waterDeptLabel))
                .addGap(33, 33, 33)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payGasBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageGazBillLabel)
                    .addComponent(gasDeptLabel))
                .addGap(33, 33, 33)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(payInternetBillButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(messageInternetBillLabel)
                    .addComponent(internetDeptLabel))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(paymentPanelLayout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(messageElecBillLabel)
                    .addContainerGap(335, Short.MAX_VALUE)))
        );

        paymentPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {electricDeptLabel, gasDeptLabel, internetDeptLabel, messageGazBillLabel, messageInternetBillLabel, messagelWaterBillLabel, payElectricityBillButton, waterDeptLabel});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void payElectricityBillButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payElectricityBillButtonMouseEntered
        ButtonSetting.setBgFg(payElectricityBillButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_payElectricityBillButtonMouseEntered

    private void payElectricityBillButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payElectricityBillButtonMouseExited
        ButtonSetting.setOriginalBgFg(payElectricityBillButton);
    }//GEN-LAST:event_payElectricityBillButtonMouseExited

    private void payWaterBillButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payWaterBillButtonMouseEntered
       ButtonSetting.setBgFg(payWaterBillButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_payWaterBillButtonMouseEntered

    private void payWaterBillButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payWaterBillButtonMouseExited
        ButtonSetting.setOriginalBgFg(payWaterBillButton);
    }//GEN-LAST:event_payWaterBillButtonMouseExited

    private void payGasBillButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payGasBillButtonMouseEntered
        ButtonSetting.setBgFg(payGasBillButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_payGasBillButtonMouseEntered

    private void payGasBillButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payGasBillButtonMouseExited
        ButtonSetting.setOriginalBgFg(payGasBillButton);
    }//GEN-LAST:event_payGasBillButtonMouseExited

    private void payInternetBillButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payInternetBillButtonMouseEntered
         ButtonSetting.setBgFg(payInternetBillButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_payInternetBillButtonMouseEntered

    private void payInternetBillButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payInternetBillButtonMouseExited
       ButtonSetting.setOriginalBgFg(payInternetBillButton);
    }//GEN-LAST:event_payInternetBillButtonMouseExited

    private void backButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseEntered
        ButtonSetting.setBgFg(backButton, Color.CYAN, Color.blue);
    }//GEN-LAST:event_backButtonMouseEntered

    private void backButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseExited
       ButtonSetting.setOriginalBgFg(backButton);
    }//GEN-LAST:event_backButtonMouseExited

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        ActionSetting.setVisible(this, new AccountScreen());
    }//GEN-LAST:event_backButtonActionPerformed

    private void payElectricityBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payElectricityBillButtonActionPerformed
       double billAmount = Double.valueOf(this.electricDeptLabel.getText());
        if (this.billPrepaid(billAmount)) {
            Dialogs.privateMessageShow(this, "Electric bill already paid!");
        } else {
            this.payBill("elektrik", billAmount);
        }
    }//GEN-LAST:event_payElectricityBillButtonActionPerformed

    private void payWaterBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payWaterBillButtonActionPerformed
       double billAmount = Double.valueOf(this.waterDeptLabel.getText());
        if (this.billPrepaid(billAmount)) {
            Dialogs.privateMessageShow(this, "Water bill already paid!");
        } else {
            this.payBill("su", billAmount);
        }
    }//GEN-LAST:event_payWaterBillButtonActionPerformed

    private void payGasBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payGasBillButtonActionPerformed
        double billAmount = Double.valueOf(this.gasDeptLabel.getText());
        if (this.billPrepaid(billAmount)) {
            Dialogs.privateMessageShow(this, "Gas bill already paid!");
        } else {
            this.payBill("dogalgaz", billAmount);
        }
    }//GEN-LAST:event_payGasBillButtonActionPerformed

    private void payInternetBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payInternetBillButtonActionPerformed
        double billAmount = Double.valueOf(this.internetDeptLabel.getText());
        if (this.billPrepaid(billAmount)) {
            Dialogs.privateMessageShow(this, "Internet bill already paid!");
        } else {
            this.payBill("internet", billAmount);
        }
    }//GEN-LAST:event_payInternetBillButtonActionPerformed
    private boolean billPrepaid(double paymentAmount) {
        return paymentAmount == 0.0;
    }

    private void payBill(String billName, double billAmount) {
        this.getPaymentsObject().setBillName(billName);
        this.getPaymentsObject().setBillAmount(billAmount);

        if (getPaymentsObject().isTheBillPaid()) {
            Dialogs.privateMessageShow(this, "Your invoice has been successfully paid.");
             ActionSetting.setVisible(this, new AccountScreen());
        } else {
            Dialogs.privateMessageShow(this, "Payment transaction failed!");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel electricDeptLabel;
    private javax.swing.JLabel gasDeptLabel;
    private javax.swing.JLabel internetDeptLabel;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel messageElecBillLabel;
    private javax.swing.JLabel messageGazBillLabel;
    private javax.swing.JLabel messageInternetBillLabel;
    private javax.swing.JLabel messagelWaterBillLabel;
    private javax.swing.JButton payElectricityBillButton;
    private javax.swing.JButton payGasBillButton;
    private javax.swing.JButton payInternetBillButton;
    private javax.swing.JButton payWaterBillButton;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel userNameSurname;
    private javax.swing.JLabel waterDeptLabel;
    // End of variables declaration//GEN-END:variables
}
